apiVersion: v1
kind: Pod
metadata:
  name: connect-helloworld
spec:
  containers:
    - name: connect-helloworld
      image: iundarigun/connect-helloworld
      ports:
        - containerPort: 2012
      env:
        - name: "HELLOWORLD_URL"
          value: "http://helloworld.default.svc.cluster.local"